[package]
name = "num_train01_two"
version = "0.1.3"
edition = "2024"
authors = ["num-bbro <num@bbro.jp>"]
description = "num train one"
license = "MIT OR Apache-2.0"

[dependencies]
num_train01_lib = { path = "../num_train01_lib", version = "^0.1.2" }

